### ISSUE TITLE
Code for generating Julia Manual Epub

### ISSUE THREAD

**Issue by George9000** [laborg/DocumenterEpubExample#1]
Thank you for these example epub files of the Julia manual. It's helpful to have for reference, for example, on one's phone. An attempt to generate an epub file from a clone of the master branch of the Julia repository failed. The code in the DocumenterEpub README was used as a guide. Would you kindly post, perhas as a README to these examples, how they were generated with DocumenterEpub?

**Comment by laborg** [comment]
Just take a look at this branch I used to create the EPUB for Julia: https://github.com/laborg/julia/tree/createepub 
To create the epub call ´make epub´ from the ´/doc´ directory (You might need to Pkg.update() the project in the ´/doc´ directory first).

**Comment by George9000** [comment]
Thanks! Cloned, built julia first in the main directory with `make`, then changed to the doc/ dir and ran `make epub`. Imported into my Books.app on macOS and all looks good.
